name: PlayerSkillsReborn
version: 1.7.12
description: Skills
authors: [fatpigsarefat, oRIOn_Tx]
main: me.fatpigsarefat.skills.PlayerSkills
softdepend: [Citizens, HolographicDisplays]
commands:
  skills:
    description: View skills
    usage: /skills
    aliases: [skill]
  skillsadmin:
    description: Skills admin
    usage: /skillsadmin
    aliases: [skilladmin]