name: PlayerSkills
version: 2.1
description: Skills
authors: [fatpigsarefat, oRIOn_Tx, ItzJustSamu, Abdelaziz1586]
main: me.fatpigsarefat.skills.PlayerSkills
api-version: 1.13
softdepend: [Citizens, HolographicDisplays, ProtocolLib, PlaceholderAPI]
commands:
  skills:
    description: View skills
    usage: /skills
    aliases: [skill]
  skillsadmin:
    description: Skills admin
    usage: /skillsadmin
    aliases: [skilladmin]
