check-update: true
points:
  restriction: false
  restriction-per: 10
xp:
  price: 1
  add-total-to-price: true
  add-total-to-price-multiplier: 1
permissions:
  use: false
  level-perms: false
skills:
  strength:
    increment: 5
    max-level: 10
  criticals:
    increment: 5
    max-level: 10
  resistance:
    increment: 5
    max-level: 10
  archery:
    increment: 5
    max-level: 10
  health:
    increment: 5
    max-level: 10
admin-notification: true
worlds:
  restricted: false
  allowed-worlds:
    - world
    - lobby